## src/TreeConteiner/BUILD

cc_library(
    name = "TreeConteiner",
    srcs = ["TreeConteiner.cpp"],
    hdrs = ["TreeConteiner.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Tree:Tree",
        "//src/FruitTree:FruitTree",
        "//src/ForestTree:ForestTree"
    ],
)