## src/Professor/BUILD

cc_library(
    name = "Professor",
    srcs = ["ProfessorFunc.cpp"],
    hdrs = ["Professor.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/Person:Person",
    ],
)